---
- hosts: devpc

  vars:
    npm_global_directory_name: .npm-global
    npm_global_directory: "{{ ansible_user_dir }}/{{ npm_global_directory_name }}"

  tasks:
    - name: Create npm global directory
      ansible.builtin.file:
        state: directory
        path: "{{ npm_global_directory }}"

    - name: Set npm global directory in user local .npmrc file
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.npmrc"
        regexp: '^prefix='
        line: "prefix={{ npm_global_directory }}"
        state: present
        create: true
        mode: 0600

    - name: Set env var for new npm global directory in ~/.profile
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.profile"
        state: present
        block: |
          # set PATH to new local npm directory to avoid permission problems when install global packages 
          if [ -d "$HOME/{{ npm_global_directory_name }}" ] ; then
              PATH="{{ ansible_user_dir }}/.npm-global/bin:$PATH"
          fi

    - name: Check if zsh is installed.
      ansible.builtin.shell:
        cmd: which zsh
      register: which_zsh
      changed_when: false

    - name: Set env var for new npm global directory in ~/.zshenv
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.zshenv"
        state: present
        create: true
        block: |
          # set PATH to new local npm directory to avoid permission problems when install global packages 
          if [ -d "$HOME/{{ npm_global_directory_name }}" ] ; then
              PATH="{{ ansible_user_dir }}/.npm-global/bin:$PATH"
          fi
      when: which_zsh.rc == 0
