---
- hosts: devpc
  become: true

  vars:
    mpv_state: present
    krita_state: present

  tasks:
    - name: Install mpv 
      ansible.builtin.apt:
        pkg:
          - mpv
        state: "{{ mpv_state }}"
        update_cache: true
        cache_valid_time: 3600

    - name: Install Krita.
      ansible.builtin.krita:
        name: krita
        state: "{{ krita_state }}"
        update_cache: true
        cache_valid_time: 3600

